import { execSync } from 'child_process';
import { EnforcementReport, CheckResult, RetryInfo, EscalationInfo } from './enforcementReport';

export interface PRContext {
  prNumber: number;
  branch: string;
}

export interface PostPRCommentOptions {
  prNumber: number;
  body: string;
  dryRun?: boolean;
}

export interface PostPRCommentResult {
  posted: boolean;
  markdown: string;
  error?: string;
}

const MAX_COMMENT_LENGTH = 65536;

/**
 * Detect if we're in a PR context.
 * Returns PR number and branch, or null if not in a PR.
 */
export function detectPRContext(): PRContext | null {
  // Try GITHUB_REF first
  const githubRef = process.env.GITHUB_REF;
  if (githubRef) {
    const match = githubRef.match(/refs\/pull\/(\d+)\/merge/);
    if (match) {
      return {
        prNumber: parseInt(match[1], 10),
        branch: githubRef,
      };
    }
  }

  // Try gh CLI
  try {
    const output = execSync("gh pr view --json number --jq '.number'", {
      encoding: 'utf-8',
    });
    const prNumber = parseInt(output.trim(), 10);
    if (!isNaN(prNumber)) {
      return {
        prNumber,
        branch: '',
      };
    }
  } catch {
    // gh command failed or not in a PR
  }

  return null;
}

/**
 * Render an EnforcementReport as GitHub markdown.
 */
export function renderMarkdown(report: EnforcementReport): string {
  const lines: string[] = [];

  lines.push('## Vector Enforcement Report');
  lines.push('');
  lines.push(`**Blueprint:** ${report.blueprintName}`);
  lines.push(`**Task:** ${report.taskDescription}`);
  lines.push('');

  // Render checks table
  if (report.checks.length > 0) {
    lines.push('### Checks');
    lines.push('');
    lines.push('| Check | Status | Duration | Details |');
    lines.push('|-------|--------|----------|---------|');

    for (const check of report.checks) {
      const statusEmoji = getStatusEmoji(check.status);
      const statusText = check.status === 'passed' ? 'Pass' : check.status === 'failed' ? 'Fail' : 'Skip';
      const details = check.details?.message || '';
      lines.push(`| ${check.checkName} | ${statusEmoji} ${statusText} | ${check.duration}ms | ${details} |`);
    }
    lines.push('');
  }

  // Render retry details if present
  if (report.retries.length > 0) {
    const retryCount = report.retries.length;
    const retryLabel = retryCount === 1 ? '1 retry' : `${retryCount} retries`;
    lines.push(`<details>`);
    lines.push(`<summary>Retry Details (${retryLabel})</summary>`);
    lines.push('');

    for (const retry of report.retries) {
      lines.push(`**${retry.checkName}** — ${retry.totalAttempts} attempts, succeeded at #${retry.succeededAtAttempt || 'N/A'}`);
      lines.push('| Attempt | Status | Duration | Error |');
      lines.push('|---------|--------|----------|-------|');

      for (const attempt of retry.attemptHistory) {
        const statusEmoji = getStatusEmoji(attempt.status === 'passed' ? 'passed' : 'failed');
        const statusText = attempt.status === 'passed' ? 'Pass' : 'Fail';
        const error = attempt.error || '';
        lines.push(`| ${attempt.attemptNumber} | ${statusEmoji} ${statusText} | ${attempt.duration}ms | ${error} |`);
      }
      lines.push('');
    }

    lines.push('</details>');
    lines.push('');
  }

  // Render escalation if present
  if (report.escalation) {
    lines.push('### Escalation');
    lines.push('');
    lines.push(`**Reason:** ${report.escalation.reason}`);
    lines.push(`**Suggestion:** ${report.escalation.suggestion}`);
    lines.push('');
  }

  // Render verdict
  const verdictText = report.verdict === 'pass' ? 'PASS' : 'FAIL';
  const checkCount = report.checks.length;
  const retryCount = report.retries.length;
  const checkLabel = checkCount === 1 ? '1 check' : `${checkCount} checks`;
  const retryLabel = retryCount === 1 ? '1 retry' : retryCount > 0 ? `${retryCount} retries` : '0 retries';
  const duration = `${report.totalDuration}ms total`;

  lines.push(`**Verdict: ${verdictText}** — ${checkLabel}, ${retryLabel}, ${duration}`);
  lines.push('');
  lines.push('---');
  lines.push('<sub>Generated by Vector Enforcer</sub>');

  return lines.join('\n');
}

/**
 * Get GitHub emoji shortcode for a status.
 */
function getStatusEmoji(status: 'passed' | 'failed' | 'skipped'): string {
  switch (status) {
    case 'passed':
      return ':white_check_mark:';
    case 'failed':
      return ':x:';
    case 'skipped':
      return ':skip:';
    default:
      return ':question:';
  }
}

/**
 * Post a comment to a GitHub PR.
 * Returns { posted, markdown, error? }
 */
export async function postPRComment(opts: PostPRCommentOptions): Promise<PostPRCommentResult> {
  let body = opts.body;

  // Truncate if necessary
  if (body.length > MAX_COMMENT_LENGTH) {
    body = body.substring(0, MAX_COMMENT_LENGTH - 100) + '\n\n*Comment was truncated due to length limits.*';
  }

  // Dry run: don't post
  if (opts.dryRun) {
    return {
      posted: false,
      markdown: body,
    };
  }

  // Post via gh CLI
  try {
    const escapedBody = body.replace(/"/g, '\\"').replace(/\$/g, '\\$');
    execSync(`gh pr comment ${opts.prNumber} -b "${escapedBody}"`, {
      stdio: 'pipe',
    });
    return {
      posted: true,
      markdown: body,
    };
  } catch (error) {
    const errorMessage = error instanceof Error ? error.message : String(error);
    return {
      posted: false,
      markdown: body,
      error: errorMessage,
    };
  }
}
